export * from './account.service';
import { AccountService } from './account.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './chef.service';
import { ChefService } from './chef.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './meal.service';
import { MealService } from './meal.service';
export * from './oidcConfiguration.service';
import { OidcConfigurationService } from './oidcConfiguration.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './person.service';
import { PersonService } from './person.service';
export * from './review.service';
import { ReviewService } from './review.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AccountService, CategoryService, ChefService, CustomerService, MealService, OidcConfigurationService, OrderService, PersonService, ReviewService, WeatherForecastService];
