/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import {Observable} from "rxjs";

import { DateDto } from '../model/dateDto';
import { UpdateOrderStatusDto } from '../model/updateOrderStatusDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ChefService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param chefId
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefChefIdDatesDelete(chefId: string, body?: DateDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefChefIdDatesDelete(chefId: string, body?: DateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefChefIdDatesDelete(chefId: string, body?: DateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefChefIdDatesDelete(chefId: string, body?: DateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chefId === null || chefId === undefined) {
            throw new Error('Required parameter chefId was null or undefined when calling chefChefIdDatesDelete.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.delete<any>(`${this.basePath}/Chef/${encodeURIComponent(String(chefId))}/dates`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param chefId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefChefIdDatesGet(chefId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefChefIdDatesGet(chefId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefChefIdDatesGet(chefId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefChefIdDatesGet(chefId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chefId === null || chefId === undefined) {
            throw new Error('Required parameter chefId was null or undefined when calling chefChefIdDatesGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/Chef/${encodeURIComponent(String(chefId))}/dates`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param chefId
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefChefIdDatesPost(chefId: string, body?: DateDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefChefIdDatesPost(chefId: string, body?: DateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefChefIdDatesPost(chefId: string, body?: DateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefChefIdDatesPost(chefId: string, body?: DateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chefId === null || chefId === undefined) {
            throw new Error('Required parameter chefId was null or undefined when calling chefChefIdDatesPost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/Chef/${encodeURIComponent(String(chefId))}/dates`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param chefId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefChefIdGet(chefId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefChefIdGet(chefId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefChefIdGet(chefId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefChefIdGet(chefId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chefId === null || chefId === undefined) {
            throw new Error('Required parameter chefId was null or undefined when calling chefChefIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/Chef/${encodeURIComponent(String(chefId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/Chef`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param orderId
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public chefOrdersOrderIdPut(orderId: string, body?: UpdateOrderStatusDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public chefOrdersOrderIdPut(orderId: string, body?: UpdateOrderStatusDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public chefOrdersOrderIdPut(orderId: string, body?: UpdateOrderStatusDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public chefOrdersOrderIdPut(orderId: string, body?: UpdateOrderStatusDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderId === null || orderId === undefined) {
            throw new Error('Required parameter orderId was null or undefined when calling chefOrdersOrderIdPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/Chef/orders/${encodeURIComponent(String(orderId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
