/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Address { 
    id?: string;
    dateCreated?: Date;
    dateModified?: Date;
    street?: string;
    city?: string;
    county?: string;
    country?: string;
    zipCode?: string;
    streetNumber?: string;
    floor?: string;
    apartment?: string;
}