/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { DateDto } from './dateDto';
import { TimeDto } from './timeDto';
import {Meal} from "./meal";


export interface ItemMealDto {
  mealId?: string;
  quantity ?: number;
}
export interface CreateOrderDto {
    mealWithQuantities?: Array<ItemMealDto>;
    deliveryDate?: DateDto;
    deliveryTime?: TimeDto;
    observations?: string;
}
