/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateMealDto { 
    name?: string;
    description?: string;
    categoryName?: string;
    pictureUrl?: string;
    price?: number;
    ingredients?: Array<string>;
}