/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OrderStatus = 0 | 1 | 2 | 3;

export const OrderStatus = {
    PLACED: 0 as OrderStatus,
    PREPARING: 1 as OrderStatus,
    READY: 2 as OrderStatus,
    DELIVERED: 3 as OrderStatus
};
