/**
 * Neighbor Chef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { DateDto } from './dateDto';
import { TimeDto } from './timeDto';


export interface UpdateOrderDto { 
    observations?: string;
    deliveryDate?: DateDto;
    deliveryTime?: TimeDto;
    mealIds?: Array<string>;
}